### ISSUE TITLE
Excessive spam of expiretags_check cron jobs

### ISSUE THREAD

**Issue by togamid** [xyulex/wordpress-expiretags#1]
I recently encountered an issue where wp-cron was spammed with "expiretags_check" jobs. 
Additionally, the cronjobs where updated frequently, leading to a rapid increase in DB logs. 

I think this might have something to do with this line:
https://github.com/xyulex/wp-expiretags/blob/1257abde6c04f80d1e145bbce0c8506d20d6e930/expire-tags.php#L55
From how I understand https://developer.wordpress.org/reference/functions/wp_next_scheduled/ , it should test for "expiretags_check" instead of "expiretags_checkexpirations" to prevent duplicate jobs.

**Comment by xyulex** [comment]
This has been fixed. Thanks!
