### ISSUE TITLE
Does line 59 still work with the newest fix?

### ISSUE THREAD

**Issue by togamid** [xyulex/wordpress-expiretags#2]
https://github.com/xyulex/wp-expiretags/blob/dfaf7e0610012f931a45bf2dd514476b0d500d93/expire-tags.php#L59
I have about a week of PHP experience and do not know freemius, but I thought this line added the corresponding function to the wp-cron job. In any case, I think "expiretags_check" is wrong here as it is never mentioned anywhere else after the commit https://github.com/xyulex/wp-expiretags/commit/dfaf7e0610012f931a45bf2dd514476b0d500d93 .
(I haven't tested it yet, as this plugin is inactive on the server anyway)

**Comment by xyulex** [comment]
Yes, it still works
